version: '3.8'
services:
  bom-order-nodejs:
    container_name: bomorder
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
    - /usr/src/app

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - /etc
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - /var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
volumes: 
 data: {}