apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: bomtawep-dev
spec:
  selector:
    matchLabels:
      app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: ghcr.io/bomtawep/pgadmin:latest
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: bomtawep@gmail.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: B@13o01m22
          ports:
            - containerPort: 80