apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: bomtawep-dev
spec:
  selector:
   matchLabels:
    app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: ghcr.io/bomtawep/pgadmin:latest
          imagePullPolicy: Always
          env:
           - name: PGADMIN_DEFAULT_EMAIL
             value: "bomtawep@gmail.com"
           - name: PGADMIN_DEFAULT_PASSWORD
             value: "1234"
           - name: PGADMIN_PORT
             value: "80"
          ports:
            - containerPort: 80
              name: pgadminport
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
  namespace: bomtawep-dev
spec:
  selector:
   app: pgadmin
  type: NodePort
  ports:
   - port: 80
     nodePort: 30200