apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  annotations:
    description: "Deploy pgAdmin 4 web application"
objects:
- kind: DeploymentConfig
  apiVersion: apps/v1
  metadata:
    name: pgadmin
  spec:
    replicas: 1
    selector:
      app: pgadmin
    template:
      metadata:
        labels:
          app: pgadmin
      spec:
        containers:
        - name: pgadmin
          image: dpage/pgadmin4
          env:
          - name: PGADMIN_DEFAULT_EMAIL
            value: bomtawep@gmail.com
          - name: PGADMIN_DEFAULT_PASSWORD
            value: B@13o01m22
          - name: PGADMIN_LISTEN_ADDRESS
            value: 0.0.0.0
          ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
          livenessProbe:
            httpGet:
              path: /misc/ping
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /misc/ping
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
        imagePullSecrets:
        - name: myregistrykey
- kind: Route
  apiVersion: v1
  metadata:
    name: pgadmin-route
  spec:
    host: pgadmin-${PROJECT}.apps.openshiftapps.com
    to:
      kind: Service
      name: pgadmin
      weight: 100
    port:
      targetPort: 80
  status:
    ingress:
    - conditions:
      - status: "True"
        type: Admitted
